"use client";

import Link from "next/link";
import { ExternalLink, Trophy } from "lucide-react";
import { Avatar } from "@/components/base/avatar/avatar";
import { Button } from "@/components/base/buttons/button";
import { Chip } from "@/components/base/badges/chip";
import { SubmissionStatusBadge } from "@/modules/bounties/components/status-badge";
import { useDashboard } from "../hooks/use-dashboard";
import { WorkspaceLayout } from "./workspace-layout";

export function SubmissionsView() {
  const { receivedSubmissions, mySubmissions, bounties, setSubmissionStatus } = useDashboard();
  return <WorkspaceLayout title="Submissions" description="Review incoming work and track your own contributions."><section><div className="mb-3 flex items-center justify-between"><h2 className="text-headline-semibold">Review incoming work</h2><Chip color="blue" variant="caption">{receivedSubmissions.length} total</Chip></div><div className="grid gap-2">{receivedSubmissions.map((submission) => { const bounty = bounties.find((item) => item.id === submission.bountyId); return <article key={submission.id} className="card-surface p-4"><div className="flex items-start gap-3"><Avatar initials={submission.contributorAvatar} color="blue" size="lg"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-body-medium">{submission.contributorName}</p><p className="text-body-2-regular text-text-tertiary">for {bounty?.title}</p></div><SubmissionStatusBadge status={submission.status}/></div><p className="mt-3 text-body-regular text-text-secondary">{submission.pitch}</p><a href={submission.deliverableUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-body-2-medium text-accent-600">Open deliverable<ExternalLink className="size-3.5"/></a><div className="mt-4 flex flex-wrap justify-end gap-2"><Button size="xs" variant="secondary" onClick={() => setSubmissionStatus(submission.id, "rejected")}>Decline</Button><Button size="xs" variant="secondary" onClick={() => setSubmissionStatus(submission.id, "shortlisted")}>Shortlist</Button><Button size="xs" leadingIcon={Trophy} onClick={() => { if (window.confirm("Select this contributor as winner? The demo will mark the bounty completed and simulate the USDC payout.")) setSubmissionStatus(submission.id, "winner"); }}>Select winner</Button></div></div></div></article>; })}{receivedSubmissions.length === 0 && <div className="rounded-xl border border-dashed border-border-button-default py-12 text-center text-body-regular text-text-secondary">No incoming submissions yet.</div>}</div></section><section className="mt-9"><h2 className="mb-3 text-headline-semibold">Your submitted work</h2><div className="card-surface divide-y divide-separator-border">{mySubmissions.map((submission) => { const bounty = bounties.find((item) => item.id === submission.bountyId); return <Link key={submission.id} href={bounty ? `/bounties/${bounty.slug}` : "#"} className="flex items-center justify-between gap-4 p-4 hover:bg-background-secondary-hover"><div><p className="text-body-medium">{bounty?.title}</p><p className="mt-1 text-body-2-regular text-text-tertiary">Submitted {submission.submittedAt}</p></div><SubmissionStatusBadge status={submission.status}/></Link>; })}</div></section></WorkspaceLayout>;
}
